# Generated by Django 4.0.6 on 2022-07-11 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=200)),
                ('picture', models.URLField()),
                ('rent', models.FloatField()),
                ('stocks', models.IntegerField(default=0)),
            ],
        ),
    ]
