# Generated by Django 4.0.6 on 2022-07-11 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='DISP_size',
            field=models.IntegerField(blank=True, default=13),
        ),
        migrations.AddField(
            model_name='computer',
            name='HDMI_port_num',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='computer',
            name='RAM',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='computer',
            name='USB_port_num',
            field=models.IntegerField(blank=True, default=4),
        ),
        migrations.AddField(
            model_name='computer',
            name='os',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
